USE [QFISales];
GO
IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = N'Material_Group_Name' AND Object_ID = Object_ID(N'dbo.Material Master'))
BEGIN
    ALTER TABLE [dbo].[Material Master] ADD [Material_Group_Name] VARCHAR(255);
END
GO

UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG018';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR129';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'FROZEN' WHERE [Material] = 'FGFRZ001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG021';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG016';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB011';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR023';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR025';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG022';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG023';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG017';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR148';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR137';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR138';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR139';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR140';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB015';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR024';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG014';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG010';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG009';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG008';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG006';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR037';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR036';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR033';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR032';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR031';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR030';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR029';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR028';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR027';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR026';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR025';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR024';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR023';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR125';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR123';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR076';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR075';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR074';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Jareesh Retail' WHERE [Material] = 'FGJAR003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Jareesh Retail' WHERE [Material] = 'FGJAR002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Jareesh Retail' WHERE [Material] = 'FGJAR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Jareesh Bulk' WHERE [Material] = 'FGJAB001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Harees Retail' WHERE [Material] = 'FGHAR004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Harees Retail' WHERE [Material] = 'FGHAR003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Harees Retail' WHERE [Material] = 'FGHAR002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Harees Retail' WHERE [Material] = 'FGHAR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Harees Bulk' WHERE [Material] = 'FGHAB003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Harees Bulk' WHERE [Material] = 'FGHAB002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Harees Bulk' WHERE [Material] = 'FGHAB001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 3 Retail' WHERE [Material] = 'FGFWR009';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 3 Retail' WHERE [Material] = 'FGFWR007';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 3 Retail' WHERE [Material] = 'FGFWR005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 3 Retail' WHERE [Material] = 'FGFWR004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 3 Retail' WHERE [Material] = 'FGFWR003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR027';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR026';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR021';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR020';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR019';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR018';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR017';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR016';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR013';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR012';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR011';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR010';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR009';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR008';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR007';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR016';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR015';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR014';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR012';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR011';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR010';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR009';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR008';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR007';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR006';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR013';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR012';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR011';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR010';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR009';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR008';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR007';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR006';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Retail' WHERE [Material] = 'FGCAR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG015';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG007';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR038';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR021';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR020';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR018';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR017';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR016';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR015';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR014';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR013';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR012';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR011';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR009';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR008';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR007';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR006';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Bulk' WHERE [Material] = 'FGFCB002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Bulk' WHERE [Material] = 'FGFCB001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR042';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR043';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR044';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR045';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR048';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR049';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR084';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR085';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR096';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR124';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR053';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR050';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR051';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR054';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR064';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR055';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR014';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Clean Wheat Retail' WHERE [Material] = 'FGCWR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Fine Bran Retail' WHERE [Material] = 'FGFBR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Fine Bran Retail' WHERE [Material] = 'FGFBR002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB006';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR022';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 3 Retail' WHERE [Material] = 'FGFWR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 3 Retail' WHERE [Material] = 'FGFWR002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR014';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR015';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR006';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR098';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR106';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR118';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR097';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR069';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR073';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Chakki Atta Bulk' WHERE [Material] = 'FGCAB001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Fine Bran Bulk' WHERE [Material] = 'FGFBB001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR111';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR112';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR010';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'FLOUR NO. 3' WHERE [Material] = 'FGFWB001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR028';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Retail' WHERE [Material] = 'FGFCR013';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 3 Retail' WHERE [Material] = 'FGFWR008';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 3 Retail' WHERE [Material] = 'FGFWR006';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Semolina Retail' WHERE [Material] = 'FGSMR005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Semolina Retail' WHERE [Material] = 'FGSMR004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Semolina Retail' WHERE [Material] = 'FGSMR003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Semolina Retail' WHERE [Material] = 'FGSMR001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Semolina Retail' WHERE [Material] = 'FGSMR002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR022';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG013';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG012';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG011';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB010';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 2 Bulk' WHERE [Material] = 'FGFCB003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB009';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB014';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB013';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB008';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB012';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'BULK PACK ACID OIL' WHERE [Material] = 'FGBPAO001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'BULK PACK FATTY ACID' WHERE [Material] = 'FGBPFA001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR143';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR144';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR145';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR035';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR034';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR029';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG024';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG019';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG020';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR030';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR031';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR032';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR033';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR039';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR040';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR041';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR042';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR043';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR149';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR006';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR008';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR009';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR010';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR011';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR012';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR013';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR015';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR016';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR019';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR020';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR027';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR036';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Bulk' WHERE [Material] = 'FGFPB016';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR151';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Sugar' WHERE [Material] = 'FGSUG025';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC06';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC07';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC08';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC09';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC10';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC11';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR044';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR045';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR046';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR047';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR048';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR049';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR050';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR051';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR037';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR039';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC01';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC03';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC04';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC02';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC12';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC13';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR052';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL001';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL004';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL005';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL006';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR040';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC05';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR053';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR154';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR152';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR147';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR146';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR141';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR136';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR135';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR134';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR133';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR132';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR131';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR130';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR128';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR127';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR126';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR122';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR121';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR120';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR119';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR117';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR116';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR115';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR114';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR110';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR109';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR108';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR107';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR105';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR102';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR101';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR100';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR099';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR095';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR094';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR093';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR086';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR083';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR082';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR081';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR080';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR079';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR078';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR077';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR072';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR070';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR068';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR066';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR065';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR063';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR062';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR061';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR060';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR059';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR058';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR057';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR056';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR052';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR041';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR040';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR039';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR038';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR037';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR036';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR035';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR034';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR033';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR032';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR031';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR030';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR029';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR028';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR025';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR023';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR018';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR017';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL007';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR038';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL008';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL009';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL010';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL011';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL012';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL013';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'BULK PACK FATTY ACID' WHERE [Material] = 'FGBPFA003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'BULK PACK FATTY ACID' WHERE [Material] = 'FGBPFA002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'BULK PACK ACID OIL' WHERE [Material] = 'FGBPAO003';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'BULK PACK ACID OIL' WHERE [Material] = 'FGBPAO002';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR150';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR113';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR104';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR103';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR071';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR067';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR047';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR046';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR022';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR021';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Flour 1 Retail' WHERE [Material] = 'FGFPR041';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL014';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'PULSES' WHERE [Material] = 'FGPUL015';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC14';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC15';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Pasta Retail' WHERE [Material] = 'FGPAR019';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC16';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC17';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'RICE' WHERE [Material] = 'FGRIC18';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR155';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR142';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR157';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR156';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR158';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR159';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR160';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR163';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR164';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR161';
UPDATE [dbo].[Material Master] SET [Material_Group_Name] = 'Oil & Fat' WHERE [Material] = 'FGOFR162';
